version: '3s'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/transcend-backend-services:ro
    environment:
      - DATABASE_URL=postgresql://karlostuazon:password@db:5432/testdb
    ports:
      - "8000:80"

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=karlostuazon
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb

volumes:
  postgres_data: