import os
from dotenv import load_dotenv
load_dotenv()

# Firebase Config 
FIREBASE_CONFIG_APIKEY=os.getenv("FIREBASE_CONFIG_APIKEY")
FIREBASE_CONFIG_AUTHDOMAIN=os.getenv("FIREBASE_CONFIG_AUTHDOMAIN")
FIREBASE_CONFIG_PROJECTID=os.getenv("FIREBASE_CONFIG_PROJECTID")
FIREBASE_CONFIG_STORAGEBUCKET=os.getenv("FIREBASE_CONFIG_STORAGEBUCKET")
FIREBASE_CONFIG_MESSAGINGSENDERID=os.getenv("FIREBASE_CONFIG_MESSAGINGSENDERID")
FIREBASE_CONFIG_APPID=os.getenv("FIREBASE_CONFIG_APPID")
FIREBASE_CONFIG_MEASUREMENTID= os.getenv("FIREBASE_CONFIG_MEASUREMENTID")

#Postresql Connection Config
DATABASE_URL=os.getenv('DATABASE_URL')
