import os
from dotenv import load_dotenv
load_dotenv()

# Firebase Config 
FIREBASE_CONFIG_APIKEY=os.getenv("FIREBASE_CONFIG_APIKEY")
FIREBASE_CONFIG_AUTHDOMAIN=os.getenv("FIREBASE_CONFIG_AUTHDOMAIN")
FIREBASE_CONFIG_PROJECTID=os.getenv("FIREBASE_CONFIG_PROJECTID")
FIREBASE_CONFIG_STORAGEBUCKET=os.getenv("FIREBASE_CONFIG_STORAGEBUCKET")
FIREBASE_CONFIG_MESSAGINGSENDERID=os.getenv("FIREBASE_CONFIG_MESSAGINGSENDERID")
FIREBASE_CONFIG_APPID=os.getenv("FIREBASE_CONFIG_APPID")
FIREBASE_CONFIG_MEASUREMENTID= os.getenv("FIREBASE_CONFIG_MEASUREMENTID")

#Postresql Connection Config
SQLALCHEMY_DATABASE_URL=os.getenv('SQLALCHEMY_DATABASE_URL')

#Email Credentials
EMAIL_USERNAME = os.getenv('EMAIL_USERNAME')
EMAIL_PASSWORD = os.getenv('EMAIL_PASSWORD')
EMAIL_FROM = os.getenv('EMAIL_FROM')
EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
EMAIL_SERVER = os.getenv('EMAIL_SERVER')
EMAIL_FROM_NAME = os.getenv('EMAIL_FROM_NAME')

#Web App URLs
DEV_URL = os.getenv('DEV_URL')
STAGING_URL = os.getenv('STAGING_URL')
