name: Staging Environment

on:
  push:
    tags:
      - "staging/v*"

#A workflow job running sequentially
jobs:
  build:
    #runs-on: defines The workflow runner
    runs-on: ubuntu-latest
    #steps: defines a series of tasks executed by the Job
    steps:
      - uses: actions/checkout@v2
      - run: | # To fetch all history for all tags and branches
          git fetch --prune --unshallow

      #Task for setting up Python 3.10 using actions/setup-python@v2 Github action
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.12"
          architecture: "x64"

      #Task for installing dependencies, multi-line command
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Task for linting with black
      - name: Lint with black
        run: |
          # Code formatting with black, check every python file in the src directory 
          black app
          black --check app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Render
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_STAGING }}
        run: |
          curl "$deploy_url"
